# Generated by Django 5.0.1 on 2024-01-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="img",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
